# SPDX-License-Identifier: Apache-2.0
name: Project Board Backfill

on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * *"

permissions:
  contents: read

jobs:
  backfill:
    uses: lpasquali/rune-ci/.github/workflows/project-backfill-logic.yml@72ffc70b5253c30afd47b06e81eff3f9b08c04c8
    secrets:
      PROJECT_TOKEN: ${{ secrets.PROJECT_TOKEN }}
